<div class="min-h-screen flex items-center justify-center p-4">
    <div class="flex flex-col gap-6 sm:w-1/2 md:w-1/4 lg:w-1/5 mx-auto">
        <x-auth-header :title="__('Two Factor Recovery')" :description="__('Verify using the code generated by your Authentication App')" />
        <x-auth-session-status class="text-center" :status="session('status')" />
        <x-auth-session-status class="text-center text-red-600" :status="session('error')" />
        <form wire:submit="verify" class="flex flex-col gap-6">
            <flux:input wire:model="code" :label="__('Two Factor Authentication Recovery Code')" type="text"
                placeholder="**********-**********" />

            <div class="grid grid-cols-1  gap-4 w-full">
                <flux:button variant="primary" icon="arrow-right-end-on-rectangle" type="submit" class="w-full">
                    {{ __('Log in') }}
                </flux:button>

            </div>
        </form>
        <form method="POST" action="{{ route('logout') }}" class="w-full">
            @csrf
            <flux:button variant="danger" class="w-full" type="submit" icon="arrow-left-end-on-rectangle">Logout
            </flux:button>
        </form>
    </div>
</div>
