<section class="w-full">
    @include('partials.settings-heading')

    <x-settings.layout :heading="__('Two factor Authentication')" :subheading=" __('Enable or disable two factor authentication for your account')">
        @if (!Auth::user()->two_factor_secret_app)
            @if ($showQrCode)
                <div class="mt-4 space-y-4">
                    <p class="text-zinc-700">Scan the QR Code with your authentication app.</p>
                    {!! $qrCodeUrl !!}


                    <flux:input type="text" wire:model="code" label="Enter the Code Generated by the Authentication App"
                        class="w-full" />

                    <div class="grid grid-cols-2 gap-4">
                        <flux:button variant="primary" wire:click='enableTwoFactor' class="w-full">
                            {{ __('Enable Two Factor Authentication') }}
                        </flux:button>
                        <flux:button variant="danger" wire:click='toggleQrCode' class="w-full">
                            {{ __('Hide QR Code') }}
                        </flux:button>
                    </div>

                </div>
            @else
                <div class="mt-4 space-y-4">
                    <p class="text-zinc-700">Click the bottom below to show the QR Code.</p>
                    <flux:button variant="primary" wire:click='toggleQrCode' class="w-full">
                        {{ __('Show QR Code') }}
                    </flux:button>
                </div>
            @endif

        @else
            <div class="mt-4 space-y-4">
                <p class="text-zinc-700"> Your Two Factor Authentication is enabled.</p>
                <flux:button variant="danger" wire:click='disableTwoFactor' class="w-full">
                    {{ __('Disable Two Factor Authentication') }}
                </flux:button>
                @if (!$showingRecoveryCodes)
                    <flux:button variant="primary" wire:click='toggleRecoveryCodes' class="w-full">
                        {{ __('Show Recovery Codes') }}
                    </flux:button>
                @else
                    <ul class="grid grid-cols-2 gap-2 mt-4 list-none">
                        @foreach (json_decode($recoveryCodes) as $code)
                            <li class="px-3 py-2 bg-zinc-100 rounded font-mono text-sm text-zinc-700 break-all">
                                {{ $code }}
                            </li>
                        @endforeach
                    </ul>
                    <flux:button variant="danger" wire:click='disableTwoFactor' class="w-full">
                        {{ __('Hide Recovery Codes') }}
                    </flux:button>
                @endif

            </div>
        @endif
    </x-settings.layout>
</section>
